/*
 * Tower SDK API
 * cloudtower operation API and SDK
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartx.tower.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.smartx.tower.model.BrickPhaseEnum;
import com.smartx.tower.model.Direction;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * BrickTopoDiskLayout
 */
@JsonPropertyOrder({
  BrickTopoDiskLayout.JSON_PROPERTY_ROW,
  BrickTopoDiskLayout.JSON_PROPERTY_PHASE,
  BrickTopoDiskLayout.JSON_PROPERTY_DIRECTION,
  BrickTopoDiskLayout.JSON_PROPERTY_COLUMN
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T15:59:14.939791800+08:00[Asia/Shanghai]")
public class BrickTopoDiskLayout {
  public static final String JSON_PROPERTY_ROW = "row";
  private Double row;

  public static final String JSON_PROPERTY_PHASE = "phase";
  private BrickPhaseEnum phase;

  public static final String JSON_PROPERTY_DIRECTION = "direction";
  private Direction direction;

  public static final String JSON_PROPERTY_COLUMN = "column";
  private Double column;


  public BrickTopoDiskLayout row(Double row) {
    this.row = row;
    return this;
  }

   /**
   * Get row
   * @return row
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ROW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getRow() {
    return row;
  }


  @JsonProperty(JSON_PROPERTY_ROW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRow(Double row) {
    this.row = row;
  }


  public BrickTopoDiskLayout phase(BrickPhaseEnum phase) {
    this.phase = phase;
    return this;
  }

   /**
   * Get phase
   * @return phase
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PHASE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BrickPhaseEnum getPhase() {
    return phase;
  }


  @JsonProperty(JSON_PROPERTY_PHASE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPhase(BrickPhaseEnum phase) {
    this.phase = phase;
  }


  public BrickTopoDiskLayout direction(Direction direction) {
    this.direction = direction;
    return this;
  }

   /**
   * Get direction
   * @return direction
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DIRECTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Direction getDirection() {
    return direction;
  }


  @JsonProperty(JSON_PROPERTY_DIRECTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDirection(Direction direction) {
    this.direction = direction;
  }


  public BrickTopoDiskLayout column(Double column) {
    this.column = column;
    return this;
  }

   /**
   * Get column
   * @return column
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COLUMN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getColumn() {
    return column;
  }


  @JsonProperty(JSON_PROPERTY_COLUMN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setColumn(Double column) {
    this.column = column;
  }


  /**
   * Return true if this BrickTopo_disk_layout object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrickTopoDiskLayout brickTopoDiskLayout = (BrickTopoDiskLayout) o;
    return Objects.equals(this.row, brickTopoDiskLayout.row) &&
        Objects.equals(this.phase, brickTopoDiskLayout.phase) &&
        Objects.equals(this.direction, brickTopoDiskLayout.direction) &&
        Objects.equals(this.column, brickTopoDiskLayout.column);
  }

  @Override
  public int hashCode() {
    return Objects.hash(row, phase, direction, column);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrickTopoDiskLayout {\n");
    sb.append("    row: ").append(toIndentedString(row)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    column: ").append(toIndentedString(column)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

