/*
 * Tower SDK API
 * cloudtower operation API and SDK
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartx.tower.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets EntityFilterOrderByInput
 */
public enum EntityFilterOrderByInput {
  
  APPLY_TO_ALL_CLUSTERS_ASC("apply_to_all_clusters_ASC"),
  
  APPLY_TO_ALL_CLUSTERS_DESC("apply_to_all_clusters_DESC"),
  
  CREATEDAT_ASC("createdAt_ASC"),
  
  CREATEDAT_DESC("createdAt_DESC"),
  
  ENTITY_TYPE_ASC("entity_type_ASC"),
  
  ENTITY_TYPE_DESC("entity_type_DESC"),
  
  FILTER_STATUS_ASC("filter_status_ASC"),
  
  FILTER_STATUS_DESC("filter_status_DESC"),
  
  ID_ASC("id_ASC"),
  
  ID_DESC("id_DESC"),
  
  LAST_EXECUTED_AT_ASC("last_executed_at_ASC"),
  
  LAST_EXECUTED_AT_DESC("last_executed_at_DESC"),
  
  NAME_ASC("name_ASC"),
  
  NAME_DESC("name_DESC"),
  
  PRESET_ASC("preset_ASC"),
  
  PRESET_DESC("preset_DESC"),
  
  RULES_ASC("rules_ASC"),
  
  RULES_DESC("rules_DESC"),
  
  UPDATEDAT_ASC("updatedAt_ASC"),
  
  UPDATEDAT_DESC("updatedAt_DESC");

  private String value;

  EntityFilterOrderByInput(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static EntityFilterOrderByInput fromValue(String value) {
    for (EntityFilterOrderByInput b : EntityFilterOrderByInput.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

