/*
 * Tower SDK API
 * cloudtower operation API and SDK
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartx.tower.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * EverouteClusterControllerTemplate
 */
@JsonPropertyOrder({
  EverouteClusterControllerTemplate.JSON_PROPERTY_VCPU,
  EverouteClusterControllerTemplate.JSON_PROPERTY_SIZE,
  EverouteClusterControllerTemplate.JSON_PROPERTY_NETMASK,
  EverouteClusterControllerTemplate.JSON_PROPERTY_MEMORY,
  EverouteClusterControllerTemplate.JSON_PROPERTY_GATEWAY,
  EverouteClusterControllerTemplate.JSON_PROPERTY_CLUSTER
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T15:59:14.939791800+08:00[Asia/Shanghai]")
public class EverouteClusterControllerTemplate {
  public static final String JSON_PROPERTY_VCPU = "vcpu";
  private Double vcpu;

  public static final String JSON_PROPERTY_SIZE = "size";
  private Double size;

  public static final String JSON_PROPERTY_NETMASK = "netmask";
  private String netmask;

  public static final String JSON_PROPERTY_MEMORY = "memory";
  private Double memory;

  public static final String JSON_PROPERTY_GATEWAY = "gateway";
  private String gateway;

  public static final String JSON_PROPERTY_CLUSTER = "cluster";
  private String cluster;


  public EverouteClusterControllerTemplate vcpu(Double vcpu) {
    this.vcpu = vcpu;
    return this;
  }

   /**
   * Get vcpu
   * @return vcpu
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VCPU)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getVcpu() {
    return vcpu;
  }


  @JsonProperty(JSON_PROPERTY_VCPU)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVcpu(Double vcpu) {
    this.vcpu = vcpu;
  }


  public EverouteClusterControllerTemplate size(Double size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getSize() {
    return size;
  }


  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSize(Double size) {
    this.size = size;
  }


  public EverouteClusterControllerTemplate netmask(String netmask) {
    this.netmask = netmask;
    return this;
  }

   /**
   * Get netmask
   * @return netmask
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NETMASK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNetmask() {
    return netmask;
  }


  @JsonProperty(JSON_PROPERTY_NETMASK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNetmask(String netmask) {
    this.netmask = netmask;
  }


  public EverouteClusterControllerTemplate memory(Double memory) {
    this.memory = memory;
    return this;
  }

   /**
   * Get memory
   * @return memory
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MEMORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getMemory() {
    return memory;
  }


  @JsonProperty(JSON_PROPERTY_MEMORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMemory(Double memory) {
    this.memory = memory;
  }


  public EverouteClusterControllerTemplate gateway(String gateway) {
    this.gateway = gateway;
    return this;
  }

   /**
   * Get gateway
   * @return gateway
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_GATEWAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getGateway() {
    return gateway;
  }


  @JsonProperty(JSON_PROPERTY_GATEWAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGateway(String gateway) {
    this.gateway = gateway;
  }


  public EverouteClusterControllerTemplate cluster(String cluster) {
    this.cluster = cluster;
    return this;
  }

   /**
   * Get cluster
   * @return cluster
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CLUSTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCluster() {
    return cluster;
  }


  @JsonProperty(JSON_PROPERTY_CLUSTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCluster(String cluster) {
    this.cluster = cluster;
  }


  /**
   * Return true if this EverouteCluster_controller_template object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EverouteClusterControllerTemplate everouteClusterControllerTemplate = (EverouteClusterControllerTemplate) o;
    return Objects.equals(this.vcpu, everouteClusterControllerTemplate.vcpu) &&
        Objects.equals(this.size, everouteClusterControllerTemplate.size) &&
        Objects.equals(this.netmask, everouteClusterControllerTemplate.netmask) &&
        Objects.equals(this.memory, everouteClusterControllerTemplate.memory) &&
        Objects.equals(this.gateway, everouteClusterControllerTemplate.gateway) &&
        Objects.equals(this.cluster, everouteClusterControllerTemplate.cluster);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vcpu, size, netmask, memory, gateway, cluster);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EverouteClusterControllerTemplate {\n");
    sb.append("    vcpu: ").append(toIndentedString(vcpu)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    netmask: ").append(toIndentedString(netmask)).append("\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("    gateway: ").append(toIndentedString(gateway)).append("\n");
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

