/*
 * Tower SDK API
 * cloudtower operation API and SDK
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartx.tower.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * IscsiLunRollbackParams
 */
@JsonPropertyOrder({
  IscsiLunRollbackParams.JSON_PROPERTY_LUN_ID,
  IscsiLunRollbackParams.JSON_PROPERTY_SNAPSHOT_ID
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T15:59:14.939791800+08:00[Asia/Shanghai]")
public class IscsiLunRollbackParams {
  public static final String JSON_PROPERTY_LUN_ID = "lun_id";
  private String lunId;

  public static final String JSON_PROPERTY_SNAPSHOT_ID = "snapshot_id";
  private String snapshotId;


  public IscsiLunRollbackParams lunId(String lunId) {
    this.lunId = lunId;
    return this;
  }

   /**
   * Get lunId
   * @return lunId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LUN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLunId() {
    return lunId;
  }


  @JsonProperty(JSON_PROPERTY_LUN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLunId(String lunId) {
    this.lunId = lunId;
  }


  public IscsiLunRollbackParams snapshotId(String snapshotId) {
    this.snapshotId = snapshotId;
    return this;
  }

   /**
   * Get snapshotId
   * @return snapshotId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SNAPSHOT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSnapshotId() {
    return snapshotId;
  }


  @JsonProperty(JSON_PROPERTY_SNAPSHOT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSnapshotId(String snapshotId) {
    this.snapshotId = snapshotId;
  }


  /**
   * Return true if this IscsiLunRollbackParams object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IscsiLunRollbackParams iscsiLunRollbackParams = (IscsiLunRollbackParams) o;
    return Objects.equals(this.lunId, iscsiLunRollbackParams.lunId) &&
        Objects.equals(this.snapshotId, iscsiLunRollbackParams.snapshotId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lunId, snapshotId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IscsiLunRollbackParams {\n");
    sb.append("    lunId: ").append(toIndentedString(lunId)).append("\n");
    sb.append("    snapshotId: ").append(toIndentedString(snapshotId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

