/*
 * Tower SDK API
 * cloudtower operation API and SDK
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartx.tower.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.smartx.tower.model.SnapshotPlanExecuteType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SnapshotPlanCreationParams
 */
@JsonPropertyOrder({
  SnapshotPlanCreationParams.JSON_PROPERTY_VM_IDS,
  SnapshotPlanCreationParams.JSON_PROPERTY_EXECUTE_INTERVALS,
  SnapshotPlanCreationParams.JSON_PROPERTY_EXECUTE_PLAN_TYPE,
  SnapshotPlanCreationParams.JSON_PROPERTY_EXEC_H_M,
  SnapshotPlanCreationParams.JSON_PROPERTY_END_TIME,
  SnapshotPlanCreationParams.JSON_PROPERTY_START_TIME,
  SnapshotPlanCreationParams.JSON_PROPERTY_REMAIN_SNAPSHOT_NUM,
  SnapshotPlanCreationParams.JSON_PROPERTY_CLUSTER_ID,
  SnapshotPlanCreationParams.JSON_PROPERTY_NAME
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T15:59:14.939791800+08:00[Asia/Shanghai]")
public class SnapshotPlanCreationParams {
  public static final String JSON_PROPERTY_VM_IDS = "vm_ids";
  private List<String> vmIds = new ArrayList<>();

  public static final String JSON_PROPERTY_EXECUTE_INTERVALS = "execute_intervals";
  private List<Double> executeIntervals = new ArrayList<>();

  public static final String JSON_PROPERTY_EXECUTE_PLAN_TYPE = "execute_plan_type";
  private SnapshotPlanExecuteType executePlanType;

  public static final String JSON_PROPERTY_EXEC_H_M = "exec_h_m";
  private String execHM;

  public static final String JSON_PROPERTY_END_TIME = "end_time";
  private String endTime;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  private String startTime;

  public static final String JSON_PROPERTY_REMAIN_SNAPSHOT_NUM = "remain_snapshot_num";
  private Double remainSnapshotNum;

  public static final String JSON_PROPERTY_CLUSTER_ID = "cluster_id";
  private String clusterId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;


  public SnapshotPlanCreationParams vmIds(List<String> vmIds) {
    this.vmIds = vmIds;
    return this;
  }

  public SnapshotPlanCreationParams addVmIdsItem(String vmIdsItem) {
    this.vmIds.add(vmIdsItem);
    return this;
  }

   /**
   * Get vmIds
   * @return vmIds
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VM_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getVmIds() {
    return vmIds;
  }


  @JsonProperty(JSON_PROPERTY_VM_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVmIds(List<String> vmIds) {
    this.vmIds = vmIds;
  }


  public SnapshotPlanCreationParams executeIntervals(List<Double> executeIntervals) {
    this.executeIntervals = executeIntervals;
    return this;
  }

  public SnapshotPlanCreationParams addExecuteIntervalsItem(Double executeIntervalsItem) {
    this.executeIntervals.add(executeIntervalsItem);
    return this;
  }

   /**
   * Get executeIntervals
   * @return executeIntervals
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_EXECUTE_INTERVALS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Double> getExecuteIntervals() {
    return executeIntervals;
  }


  @JsonProperty(JSON_PROPERTY_EXECUTE_INTERVALS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExecuteIntervals(List<Double> executeIntervals) {
    this.executeIntervals = executeIntervals;
  }


  public SnapshotPlanCreationParams executePlanType(SnapshotPlanExecuteType executePlanType) {
    this.executePlanType = executePlanType;
    return this;
  }

   /**
   * Get executePlanType
   * @return executePlanType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_EXECUTE_PLAN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SnapshotPlanExecuteType getExecutePlanType() {
    return executePlanType;
  }


  @JsonProperty(JSON_PROPERTY_EXECUTE_PLAN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExecutePlanType(SnapshotPlanExecuteType executePlanType) {
    this.executePlanType = executePlanType;
  }


  public SnapshotPlanCreationParams execHM(String execHM) {
    this.execHM = execHM;
    return this;
  }

   /**
   * Get execHM
   * @return execHM
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXEC_H_M)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExecHM() {
    return execHM;
  }


  @JsonProperty(JSON_PROPERTY_EXEC_H_M)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExecHM(String execHM) {
    this.execHM = execHM;
  }


  public SnapshotPlanCreationParams endTime(String endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndTime() {
    return endTime;
  }


  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }


  public SnapshotPlanCreationParams startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }


  public SnapshotPlanCreationParams remainSnapshotNum(Double remainSnapshotNum) {
    this.remainSnapshotNum = remainSnapshotNum;
    return this;
  }

   /**
   * Get remainSnapshotNum
   * @return remainSnapshotNum
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_REMAIN_SNAPSHOT_NUM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getRemainSnapshotNum() {
    return remainSnapshotNum;
  }


  @JsonProperty(JSON_PROPERTY_REMAIN_SNAPSHOT_NUM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRemainSnapshotNum(Double remainSnapshotNum) {
    this.remainSnapshotNum = remainSnapshotNum;
  }


  public SnapshotPlanCreationParams clusterId(String clusterId) {
    this.clusterId = clusterId;
    return this;
  }

   /**
   * Get clusterId
   * @return clusterId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CLUSTER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClusterId() {
    return clusterId;
  }


  @JsonProperty(JSON_PROPERTY_CLUSTER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClusterId(String clusterId) {
    this.clusterId = clusterId;
  }


  public SnapshotPlanCreationParams name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  /**
   * Return true if this SnapshotPlanCreationParams object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SnapshotPlanCreationParams snapshotPlanCreationParams = (SnapshotPlanCreationParams) o;
    return Objects.equals(this.vmIds, snapshotPlanCreationParams.vmIds) &&
        Objects.equals(this.executeIntervals, snapshotPlanCreationParams.executeIntervals) &&
        Objects.equals(this.executePlanType, snapshotPlanCreationParams.executePlanType) &&
        Objects.equals(this.execHM, snapshotPlanCreationParams.execHM) &&
        Objects.equals(this.endTime, snapshotPlanCreationParams.endTime) &&
        Objects.equals(this.startTime, snapshotPlanCreationParams.startTime) &&
        Objects.equals(this.remainSnapshotNum, snapshotPlanCreationParams.remainSnapshotNum) &&
        Objects.equals(this.clusterId, snapshotPlanCreationParams.clusterId) &&
        Objects.equals(this.name, snapshotPlanCreationParams.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vmIds, executeIntervals, executePlanType, execHM, endTime, startTime, remainSnapshotNum, clusterId, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SnapshotPlanCreationParams {\n");
    sb.append("    vmIds: ").append(toIndentedString(vmIds)).append("\n");
    sb.append("    executeIntervals: ").append(toIndentedString(executeIntervals)).append("\n");
    sb.append("    executePlanType: ").append(toIndentedString(executePlanType)).append("\n");
    sb.append("    execHM: ").append(toIndentedString(execHM)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    remainSnapshotNum: ").append(toIndentedString(remainSnapshotNum)).append("\n");
    sb.append("    clusterId: ").append(toIndentedString(clusterId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

