/*
 * Tower SDK API
 * cloudtower operation API and SDK
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartx.tower.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.smartx.tower.model.UploadResourceType;
import com.smartx.tower.model.UploadTaskStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * UploadTask
 */
@JsonPropertyOrder({
  UploadTask.JSON_PROPERTY_ARGS,
  UploadTask.JSON_PROPERTY_CHUNK_SIZE,
  UploadTask.JSON_PROPERTY_CURRENT_CHUNK,
  UploadTask.JSON_PROPERTY_FINISHED_AT,
  UploadTask.JSON_PROPERTY_ID,
  UploadTask.JSON_PROPERTY_RESOURCE_TYPE,
  UploadTask.JSON_PROPERTY_SIZE,
  UploadTask.JSON_PROPERTY_STARTED_AT,
  UploadTask.JSON_PROPERTY_STATUS,
  UploadTask.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T15:59:14.939791800+08:00[Asia/Shanghai]")
public class UploadTask {
  public static final String JSON_PROPERTY_ARGS = "args";
  private Object args;

  public static final String JSON_PROPERTY_CHUNK_SIZE = "chunk_size";
  private Double chunkSize;

  public static final String JSON_PROPERTY_CURRENT_CHUNK = "current_chunk";
  private Double currentChunk;

  public static final String JSON_PROPERTY_FINISHED_AT = "finished_at";
  private JsonNullable<String> finishedAt = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_RESOURCE_TYPE = "resource_type";
  private UploadResourceType resourceType;

  public static final String JSON_PROPERTY_SIZE = "size";
  private Double size;

  public static final String JSON_PROPERTY_STARTED_AT = "started_at";
  private JsonNullable<String> startedAt = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_STATUS = "status";
  private UploadTaskStatus status;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  private String updatedAt;


  public UploadTask args(Object args) {
    this.args = args;
    return this;
  }

   /**
   * Get args
   * @return args
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ARGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getArgs() {
    return args;
  }


  @JsonProperty(JSON_PROPERTY_ARGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setArgs(Object args) {
    this.args = args;
  }


  public UploadTask chunkSize(Double chunkSize) {
    this.chunkSize = chunkSize;
    return this;
  }

   /**
   * Get chunkSize
   * @return chunkSize
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CHUNK_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getChunkSize() {
    return chunkSize;
  }


  @JsonProperty(JSON_PROPERTY_CHUNK_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChunkSize(Double chunkSize) {
    this.chunkSize = chunkSize;
  }


  public UploadTask currentChunk(Double currentChunk) {
    this.currentChunk = currentChunk;
    return this;
  }

   /**
   * Get currentChunk
   * @return currentChunk
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CURRENT_CHUNK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getCurrentChunk() {
    return currentChunk;
  }


  @JsonProperty(JSON_PROPERTY_CURRENT_CHUNK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrentChunk(Double currentChunk) {
    this.currentChunk = currentChunk;
  }


  public UploadTask finishedAt(String finishedAt) {
    this.finishedAt = JsonNullable.<String>of(finishedAt);
    return this;
  }

   /**
   * Get finishedAt
   * @return finishedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getFinishedAt() {
        return finishedAt.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FINISHED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFinishedAt_JsonNullable() {
    return finishedAt;
  }
  
  @JsonProperty(JSON_PROPERTY_FINISHED_AT)
  public void setFinishedAt_JsonNullable(JsonNullable<String> finishedAt) {
    this.finishedAt = finishedAt;
  }

  public void setFinishedAt(String finishedAt) {
    this.finishedAt = JsonNullable.<String>of(finishedAt);
  }


  public UploadTask id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public UploadTask resourceType(UploadResourceType resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Get resourceType
   * @return resourceType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UploadResourceType getResourceType() {
    return resourceType;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResourceType(UploadResourceType resourceType) {
    this.resourceType = resourceType;
  }


  public UploadTask size(Double size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getSize() {
    return size;
  }


  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSize(Double size) {
    this.size = size;
  }


  public UploadTask startedAt(String startedAt) {
    this.startedAt = JsonNullable.<String>of(startedAt);
    return this;
  }

   /**
   * Get startedAt
   * @return startedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getStartedAt() {
        return startedAt.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STARTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getStartedAt_JsonNullable() {
    return startedAt;
  }
  
  @JsonProperty(JSON_PROPERTY_STARTED_AT)
  public void setStartedAt_JsonNullable(JsonNullable<String> startedAt) {
    this.startedAt = startedAt;
  }

  public void setStartedAt(String startedAt) {
    this.startedAt = JsonNullable.<String>of(startedAt);
  }


  public UploadTask status(UploadTaskStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UploadTaskStatus getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(UploadTaskStatus status) {
    this.status = status;
  }


  public UploadTask updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  /**
   * Return true if this UploadTask object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UploadTask uploadTask = (UploadTask) o;
    return Objects.equals(this.args, uploadTask.args) &&
        Objects.equals(this.chunkSize, uploadTask.chunkSize) &&
        Objects.equals(this.currentChunk, uploadTask.currentChunk) &&
        equalsNullable(this.finishedAt, uploadTask.finishedAt) &&
        Objects.equals(this.id, uploadTask.id) &&
        Objects.equals(this.resourceType, uploadTask.resourceType) &&
        Objects.equals(this.size, uploadTask.size) &&
        equalsNullable(this.startedAt, uploadTask.startedAt) &&
        Objects.equals(this.status, uploadTask.status) &&
        Objects.equals(this.updatedAt, uploadTask.updatedAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(args, chunkSize, currentChunk, hashCodeNullable(finishedAt), id, resourceType, size, hashCodeNullable(startedAt), status, updatedAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UploadTask {\n");
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("    chunkSize: ").append(toIndentedString(chunkSize)).append("\n");
    sb.append("    currentChunk: ").append(toIndentedString(currentChunk)).append("\n");
    sb.append("    finishedAt: ").append(toIndentedString(finishedAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

