/*
 * Tower SDK API
 * cloudtower operation API and SDK
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartx.tower.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.smartx.tower.model.AlertRuleCluster;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Witness
 */
@JsonPropertyOrder({
  Witness.JSON_PROPERTY_CLUSTER,
  Witness.JSON_PROPERTY_CPU_HZ_PER_CORE,
  Witness.JSON_PROPERTY_DATA_IP,
  Witness.JSON_PROPERTY_ID,
  Witness.JSON_PROPERTY_LOCAL_ID,
  Witness.JSON_PROPERTY_NAME,
  Witness.JSON_PROPERTY_SYSTEM_DATA_CAPACITY,
  Witness.JSON_PROPERTY_SYSTEM_USED_DATA_SPACE,
  Witness.JSON_PROPERTY_TOTAL_CPU_CORES,
  Witness.JSON_PROPERTY_TOTAL_CPU_HZ,
  Witness.JSON_PROPERTY_TOTAL_MEMORY_BYTES
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T15:59:14.939791800+08:00[Asia/Shanghai]")
public class Witness {
  public static final String JSON_PROPERTY_CLUSTER = "cluster";
  private AlertRuleCluster cluster;

  public static final String JSON_PROPERTY_CPU_HZ_PER_CORE = "cpu_hz_per_core";
  private Double cpuHzPerCore;

  public static final String JSON_PROPERTY_DATA_IP = "data_ip";
  private String dataIp;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_LOCAL_ID = "local_id";
  private JsonNullable<String> localId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_SYSTEM_DATA_CAPACITY = "system_data_capacity";
  private Double systemDataCapacity;

  public static final String JSON_PROPERTY_SYSTEM_USED_DATA_SPACE = "system_used_data_space";
  private Double systemUsedDataSpace;

  public static final String JSON_PROPERTY_TOTAL_CPU_CORES = "total_cpu_cores";
  private Double totalCpuCores;

  public static final String JSON_PROPERTY_TOTAL_CPU_HZ = "total_cpu_hz";
  private Double totalCpuHz;

  public static final String JSON_PROPERTY_TOTAL_MEMORY_BYTES = "total_memory_bytes";
  private Double totalMemoryBytes;


  public Witness cluster(AlertRuleCluster cluster) {
    this.cluster = cluster;
    return this;
  }

   /**
   * Get cluster
   * @return cluster
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CLUSTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AlertRuleCluster getCluster() {
    return cluster;
  }


  @JsonProperty(JSON_PROPERTY_CLUSTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCluster(AlertRuleCluster cluster) {
    this.cluster = cluster;
  }


  public Witness cpuHzPerCore(Double cpuHzPerCore) {
    this.cpuHzPerCore = cpuHzPerCore;
    return this;
  }

   /**
   * Get cpuHzPerCore
   * @return cpuHzPerCore
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CPU_HZ_PER_CORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getCpuHzPerCore() {
    return cpuHzPerCore;
  }


  @JsonProperty(JSON_PROPERTY_CPU_HZ_PER_CORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCpuHzPerCore(Double cpuHzPerCore) {
    this.cpuHzPerCore = cpuHzPerCore;
  }


  public Witness dataIp(String dataIp) {
    this.dataIp = dataIp;
    return this;
  }

   /**
   * Get dataIp
   * @return dataIp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DATA_IP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDataIp() {
    return dataIp;
  }


  @JsonProperty(JSON_PROPERTY_DATA_IP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDataIp(String dataIp) {
    this.dataIp = dataIp;
  }


  public Witness id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public Witness localId(String localId) {
    this.localId = JsonNullable.<String>of(localId);
    return this;
  }

   /**
   * Get localId
   * @return localId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getLocalId() {
        return localId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LOCAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLocalId_JsonNullable() {
    return localId;
  }
  
  @JsonProperty(JSON_PROPERTY_LOCAL_ID)
  public void setLocalId_JsonNullable(JsonNullable<String> localId) {
    this.localId = localId;
  }

  public void setLocalId(String localId) {
    this.localId = JsonNullable.<String>of(localId);
  }


  public Witness name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public Witness systemDataCapacity(Double systemDataCapacity) {
    this.systemDataCapacity = systemDataCapacity;
    return this;
  }

   /**
   * Get systemDataCapacity
   * @return systemDataCapacity
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SYSTEM_DATA_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getSystemDataCapacity() {
    return systemDataCapacity;
  }


  @JsonProperty(JSON_PROPERTY_SYSTEM_DATA_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSystemDataCapacity(Double systemDataCapacity) {
    this.systemDataCapacity = systemDataCapacity;
  }


  public Witness systemUsedDataSpace(Double systemUsedDataSpace) {
    this.systemUsedDataSpace = systemUsedDataSpace;
    return this;
  }

   /**
   * Get systemUsedDataSpace
   * @return systemUsedDataSpace
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SYSTEM_USED_DATA_SPACE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getSystemUsedDataSpace() {
    return systemUsedDataSpace;
  }


  @JsonProperty(JSON_PROPERTY_SYSTEM_USED_DATA_SPACE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSystemUsedDataSpace(Double systemUsedDataSpace) {
    this.systemUsedDataSpace = systemUsedDataSpace;
  }


  public Witness totalCpuCores(Double totalCpuCores) {
    this.totalCpuCores = totalCpuCores;
    return this;
  }

   /**
   * Get totalCpuCores
   * @return totalCpuCores
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_CPU_CORES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getTotalCpuCores() {
    return totalCpuCores;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_CPU_CORES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalCpuCores(Double totalCpuCores) {
    this.totalCpuCores = totalCpuCores;
  }


  public Witness totalCpuHz(Double totalCpuHz) {
    this.totalCpuHz = totalCpuHz;
    return this;
  }

   /**
   * Get totalCpuHz
   * @return totalCpuHz
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_CPU_HZ)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getTotalCpuHz() {
    return totalCpuHz;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_CPU_HZ)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalCpuHz(Double totalCpuHz) {
    this.totalCpuHz = totalCpuHz;
  }


  public Witness totalMemoryBytes(Double totalMemoryBytes) {
    this.totalMemoryBytes = totalMemoryBytes;
    return this;
  }

   /**
   * Get totalMemoryBytes
   * @return totalMemoryBytes
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_MEMORY_BYTES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getTotalMemoryBytes() {
    return totalMemoryBytes;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_MEMORY_BYTES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalMemoryBytes(Double totalMemoryBytes) {
    this.totalMemoryBytes = totalMemoryBytes;
  }


  /**
   * Return true if this Witness object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Witness witness = (Witness) o;
    return Objects.equals(this.cluster, witness.cluster) &&
        Objects.equals(this.cpuHzPerCore, witness.cpuHzPerCore) &&
        Objects.equals(this.dataIp, witness.dataIp) &&
        Objects.equals(this.id, witness.id) &&
        equalsNullable(this.localId, witness.localId) &&
        Objects.equals(this.name, witness.name) &&
        Objects.equals(this.systemDataCapacity, witness.systemDataCapacity) &&
        Objects.equals(this.systemUsedDataSpace, witness.systemUsedDataSpace) &&
        Objects.equals(this.totalCpuCores, witness.totalCpuCores) &&
        Objects.equals(this.totalCpuHz, witness.totalCpuHz) &&
        Objects.equals(this.totalMemoryBytes, witness.totalMemoryBytes);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(cluster, cpuHzPerCore, dataIp, id, hashCodeNullable(localId), name, systemDataCapacity, systemUsedDataSpace, totalCpuCores, totalCpuHz, totalMemoryBytes);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Witness {\n");
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("    cpuHzPerCore: ").append(toIndentedString(cpuHzPerCore)).append("\n");
    sb.append("    dataIp: ").append(toIndentedString(dataIp)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    localId: ").append(toIndentedString(localId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    systemDataCapacity: ").append(toIndentedString(systemDataCapacity)).append("\n");
    sb.append("    systemUsedDataSpace: ").append(toIndentedString(systemUsedDataSpace)).append("\n");
    sb.append("    totalCpuCores: ").append(toIndentedString(totalCpuCores)).append("\n");
    sb.append("    totalCpuHz: ").append(toIndentedString(totalCpuHz)).append("\n");
    sb.append("    totalMemoryBytes: ").append(toIndentedString(totalMemoryBytes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

