/*
 * Tower SDK API
 * cloudtower operation API and SDK
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartx.tower.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartx.tower.model.AlertAlertRule;
import com.smartx.tower.model.AlertRuleCluster;
import com.smartx.tower.model.BrickTopoPowers;
import com.smartx.tower.model.CpuFanSpeedUnit;
import com.smartx.tower.model.HostState;
import com.smartx.tower.model.HostStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * Host
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-03T10:47:43.783335+08:00[Asia/Shanghai]")
public class Host {
  public static final String SERIALIZED_NAME_ACCESS_IP = "access_ip";
  @SerializedName(SERIALIZED_NAME_ACCESS_IP)
  private String accessIp;

  public static final String SERIALIZED_NAME_ALLOCATABLE_MEMORY_BYTES = "allocatable_memory_bytes";
  @SerializedName(SERIALIZED_NAME_ALLOCATABLE_MEMORY_BYTES)
  private Double allocatableMemoryBytes;

  public static final String SERIALIZED_NAME_CHUNK_ID = "chunk_id";
  @SerializedName(SERIALIZED_NAME_CHUNK_ID)
  private String chunkId;

  public static final String SERIALIZED_NAME_CLUSTER = "cluster";
  @SerializedName(SERIALIZED_NAME_CLUSTER)
  private AlertRuleCluster cluster;

  public static final String SERIALIZED_NAME_COMPATIBLE_CPU_MODELS = "compatible_cpu_models";
  @SerializedName(SERIALIZED_NAME_COMPATIBLE_CPU_MODELS)
  private List<String> compatibleCpuModels = new ArrayList<String>();

  public static final String SERIALIZED_NAME_CPU_BRAND = "cpu_brand";
  @SerializedName(SERIALIZED_NAME_CPU_BRAND)
  private String cpuBrand;

  public static final String SERIALIZED_NAME_CPU_FAN_SPEED = "cpu_fan_speed";
  @SerializedName(SERIALIZED_NAME_CPU_FAN_SPEED)
  private List<Double> cpuFanSpeed = new ArrayList<Double>();

  public static final String SERIALIZED_NAME_CPU_FAN_SPEED_UNIT = "cpu_fan_speed_unit";
  @SerializedName(SERIALIZED_NAME_CPU_FAN_SPEED_UNIT)
  private CpuFanSpeedUnit cpuFanSpeedUnit;

  public static final String SERIALIZED_NAME_CPU_HZ_PER_CORE = "cpu_hz_per_core";
  @SerializedName(SERIALIZED_NAME_CPU_HZ_PER_CORE)
  private Double cpuHzPerCore;

  public static final String SERIALIZED_NAME_CPU_MODEL = "cpu_model";
  @SerializedName(SERIALIZED_NAME_CPU_MODEL)
  private String cpuModel;

  public static final String SERIALIZED_NAME_CPU_TEMPERATURE_CELSIUS = "cpu_temperature_celsius";
  @SerializedName(SERIALIZED_NAME_CPU_TEMPERATURE_CELSIUS)
  private List<Double> cpuTemperatureCelsius = new ArrayList<Double>();

  public static final String SERIALIZED_NAME_DATA_IP = "data_ip";
  @SerializedName(SERIALIZED_NAME_DATA_IP)
  private String dataIp;

  public static final String SERIALIZED_NAME_DISKS = "disks";
  @SerializedName(SERIALIZED_NAME_DISKS)
  private List<AlertRuleCluster> disks = null;

  public static final String SERIALIZED_NAME_FAILURE_DATA_SPACE = "failure_data_space";
  @SerializedName(SERIALIZED_NAME_FAILURE_DATA_SPACE)
  private Double failureDataSpace;

  public static final String SERIALIZED_NAME_HDD_DATA_CAPACITY = "hdd_data_capacity";
  @SerializedName(SERIALIZED_NAME_HDD_DATA_CAPACITY)
  private Double hddDataCapacity;

  public static final String SERIALIZED_NAME_HDD_DISK_COUNT = "hdd_disk_count";
  @SerializedName(SERIALIZED_NAME_HDD_DISK_COUNT)
  private Double hddDiskCount;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_IPMI = "ipmi";
  @SerializedName(SERIALIZED_NAME_IPMI)
  private AlertAlertRule ipmi;

  public static final String SERIALIZED_NAME_IS_OS_IN_RAID1 = "is_os_in_raid1";
  @SerializedName(SERIALIZED_NAME_IS_OS_IN_RAID1)
  private Boolean isOsInRaid1;

  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  private List<BrickTopoPowers> labels = null;

  public static final String SERIALIZED_NAME_LOCAL_ID = "local_id";
  @SerializedName(SERIALIZED_NAME_LOCAL_ID)
  private String localId;

  public static final String SERIALIZED_NAME_LSM_CAP_DISK_SAFE_UMOUNT = "lsm_cap_disk_safe_umount";
  @SerializedName(SERIALIZED_NAME_LSM_CAP_DISK_SAFE_UMOUNT)
  private Boolean lsmCapDiskSafeUmount;

  public static final String SERIALIZED_NAME_MANAGEMENT_IP = "management_ip";
  @SerializedName(SERIALIZED_NAME_MANAGEMENT_IP)
  private String managementIp;

  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  private String model;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NESTED_VIRTUALIZATION = "nested_virtualization";
  @SerializedName(SERIALIZED_NAME_NESTED_VIRTUALIZATION)
  private Boolean nestedVirtualization;

  public static final String SERIALIZED_NAME_NIC_COUNT = "nic_count";
  @SerializedName(SERIALIZED_NAME_NIC_COUNT)
  private Double nicCount;

  public static final String SERIALIZED_NAME_NICS = "nics";
  @SerializedName(SERIALIZED_NAME_NICS)
  private List<AlertRuleCluster> nics = null;

  public static final String SERIALIZED_NAME_NODE_TOPO_LOCAL_ID = "node_topo_local_id";
  @SerializedName(SERIALIZED_NAME_NODE_TOPO_LOCAL_ID)
  private String nodeTopoLocalId;

  public static final String SERIALIZED_NAME_OS_MEMORY_BYTES = "os_memory_bytes";
  @SerializedName(SERIALIZED_NAME_OS_MEMORY_BYTES)
  private Double osMemoryBytes;

  public static final String SERIALIZED_NAME_OS_VERSION = "os_version";
  @SerializedName(SERIALIZED_NAME_OS_VERSION)
  private String osVersion;

  public static final String SERIALIZED_NAME_PMEM_DIMM_CAPACITY = "pmem_dimm_capacity";
  @SerializedName(SERIALIZED_NAME_PMEM_DIMM_CAPACITY)
  private Double pmemDimmCapacity;

  public static final String SERIALIZED_NAME_PMEM_DIMM_COUNT = "pmem_dimm_count";
  @SerializedName(SERIALIZED_NAME_PMEM_DIMM_COUNT)
  private Double pmemDimmCount;

  public static final String SERIALIZED_NAME_PMEM_DIMMS = "pmem_dimms";
  @SerializedName(SERIALIZED_NAME_PMEM_DIMMS)
  private List<AlertRuleCluster> pmemDimms = null;

  public static final String SERIALIZED_NAME_PMEM_DISK_COUNT = "pmem_disk_count";
  @SerializedName(SERIALIZED_NAME_PMEM_DISK_COUNT)
  private Double pmemDiskCount;

  public static final String SERIALIZED_NAME_PROVISIONED_CPU_CORES = "provisioned_cpu_cores";
  @SerializedName(SERIALIZED_NAME_PROVISIONED_CPU_CORES)
  private Double provisionedCpuCores;

  public static final String SERIALIZED_NAME_PROVISIONED_MEMORY_BYTES = "provisioned_memory_bytes";
  @SerializedName(SERIALIZED_NAME_PROVISIONED_MEMORY_BYTES)
  private Double provisionedMemoryBytes;

  public static final String SERIALIZED_NAME_RUNNING_PAUSE_VM_MEMORY_BYTES = "running_pause_vm_memory_bytes";
  @SerializedName(SERIALIZED_NAME_RUNNING_PAUSE_VM_MEMORY_BYTES)
  private Double runningPauseVmMemoryBytes;

  public static final String SERIALIZED_NAME_RUNNING_VM_NUM = "running_vm_num";
  @SerializedName(SERIALIZED_NAME_RUNNING_VM_NUM)
  private Double runningVmNum;

  public static final String SERIALIZED_NAME_SCVM_CPU = "scvm_cpu";
  @SerializedName(SERIALIZED_NAME_SCVM_CPU)
  private Double scvmCpu;

  public static final String SERIALIZED_NAME_SCVM_MEMORY = "scvm_memory";
  @SerializedName(SERIALIZED_NAME_SCVM_MEMORY)
  private Double scvmMemory;

  public static final String SERIALIZED_NAME_SCVM_NAME = "scvm_name";
  @SerializedName(SERIALIZED_NAME_SCVM_NAME)
  private String scvmName;

  public static final String SERIALIZED_NAME_SERIAL = "serial";
  @SerializedName(SERIALIZED_NAME_SERIAL)
  private String serial;

  public static final String SERIALIZED_NAME_SSD_DATA_CAPACITY = "ssd_data_capacity";
  @SerializedName(SERIALIZED_NAME_SSD_DATA_CAPACITY)
  private Double ssdDataCapacity;

  public static final String SERIALIZED_NAME_SSD_DISK_COUNT = "ssd_disk_count";
  @SerializedName(SERIALIZED_NAME_SSD_DISK_COUNT)
  private Double ssdDiskCount;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private HostState state;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private HostStatus status;

  public static final String SERIALIZED_NAME_STOPPED_VM_NUM = "stopped_vm_num";
  @SerializedName(SERIALIZED_NAME_STOPPED_VM_NUM)
  private Double stoppedVmNum;

  public static final String SERIALIZED_NAME_SUSPENDED_VM_NUM = "suspended_vm_num";
  @SerializedName(SERIALIZED_NAME_SUSPENDED_VM_NUM)
  private Double suspendedVmNum;

  public static final String SERIALIZED_NAME_TOTAL_CACHE_CAPACITY = "total_cache_capacity";
  @SerializedName(SERIALIZED_NAME_TOTAL_CACHE_CAPACITY)
  private Double totalCacheCapacity;

  public static final String SERIALIZED_NAME_TOTAL_CPU_CORES = "total_cpu_cores";
  @SerializedName(SERIALIZED_NAME_TOTAL_CPU_CORES)
  private Double totalCpuCores;

  public static final String SERIALIZED_NAME_TOTAL_CPU_HZ = "total_cpu_hz";
  @SerializedName(SERIALIZED_NAME_TOTAL_CPU_HZ)
  private Double totalCpuHz;

  public static final String SERIALIZED_NAME_TOTAL_DATA_CAPACITY = "total_data_capacity";
  @SerializedName(SERIALIZED_NAME_TOTAL_DATA_CAPACITY)
  private Double totalDataCapacity;

  public static final String SERIALIZED_NAME_TOTAL_MEMORY_BYTES = "total_memory_bytes";
  @SerializedName(SERIALIZED_NAME_TOTAL_MEMORY_BYTES)
  private Double totalMemoryBytes;

  public static final String SERIALIZED_NAME_USB_DEVICES = "usb_devices";
  @SerializedName(SERIALIZED_NAME_USB_DEVICES)
  private List<AlertRuleCluster> usbDevices = null;

  public static final String SERIALIZED_NAME_USED_CPU_HZ = "used_cpu_hz";
  @SerializedName(SERIALIZED_NAME_USED_CPU_HZ)
  private Double usedCpuHz;

  public static final String SERIALIZED_NAME_USED_DATA_SPACE = "used_data_space";
  @SerializedName(SERIALIZED_NAME_USED_DATA_SPACE)
  private Double usedDataSpace;

  public static final String SERIALIZED_NAME_USED_MEMORY_BYTES = "used_memory_bytes";
  @SerializedName(SERIALIZED_NAME_USED_MEMORY_BYTES)
  private Double usedMemoryBytes;

  public static final String SERIALIZED_NAME_VM_NUM = "vm_num";
  @SerializedName(SERIALIZED_NAME_VM_NUM)
  private Double vmNum;

  public static final String SERIALIZED_NAME_VMOTION_IP = "vmotion_ip";
  @SerializedName(SERIALIZED_NAME_VMOTION_IP)
  private String vmotionIp;

  public static final String SERIALIZED_NAME_VMS = "vms";
  @SerializedName(SERIALIZED_NAME_VMS)
  private List<AlertRuleCluster> vms = null;

  public static final String SERIALIZED_NAME_VSPHERE_ESXI_ACCOUNT = "vsphereEsxiAccount";
  @SerializedName(SERIALIZED_NAME_VSPHERE_ESXI_ACCOUNT)
  private AlertAlertRule vsphereEsxiAccount;

  public static final String SERIALIZED_NAME_WITH_FASTER_SSD_AS_CACHE = "with_faster_ssd_as_cache";
  @SerializedName(SERIALIZED_NAME_WITH_FASTER_SSD_AS_CACHE)
  private Boolean withFasterSsdAsCache;

  public static final String SERIALIZED_NAME_ZONE = "zone";
  @SerializedName(SERIALIZED_NAME_ZONE)
  private AlertAlertRule zone;


  public Host accessIp(String accessIp) {
    
    this.accessIp = accessIp;
    return this;
  }

   /**
   * Get accessIp
   * @return accessIp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAccessIp() {
    return accessIp;
  }


  public void setAccessIp(String accessIp) {
    this.accessIp = accessIp;
  }


  public Host allocatableMemoryBytes(Double allocatableMemoryBytes) {
    
    this.allocatableMemoryBytes = allocatableMemoryBytes;
    return this;
  }

   /**
   * Get allocatableMemoryBytes
   * @return allocatableMemoryBytes
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getAllocatableMemoryBytes() {
    return allocatableMemoryBytes;
  }


  public void setAllocatableMemoryBytes(Double allocatableMemoryBytes) {
    this.allocatableMemoryBytes = allocatableMemoryBytes;
  }


  public Host chunkId(String chunkId) {
    
    this.chunkId = chunkId;
    return this;
  }

   /**
   * Get chunkId
   * @return chunkId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getChunkId() {
    return chunkId;
  }


  public void setChunkId(String chunkId) {
    this.chunkId = chunkId;
  }


  public Host cluster(AlertRuleCluster cluster) {
    
    this.cluster = cluster;
    return this;
  }

   /**
   * Get cluster
   * @return cluster
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public AlertRuleCluster getCluster() {
    return cluster;
  }


  public void setCluster(AlertRuleCluster cluster) {
    this.cluster = cluster;
  }


  public Host compatibleCpuModels(List<String> compatibleCpuModels) {
    
    this.compatibleCpuModels = compatibleCpuModels;
    return this;
  }

  public Host addCompatibleCpuModelsItem(String compatibleCpuModelsItem) {
    this.compatibleCpuModels.add(compatibleCpuModelsItem);
    return this;
  }

   /**
   * Get compatibleCpuModels
   * @return compatibleCpuModels
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<String> getCompatibleCpuModels() {
    return compatibleCpuModels;
  }


  public void setCompatibleCpuModels(List<String> compatibleCpuModels) {
    this.compatibleCpuModels = compatibleCpuModels;
  }


  public Host cpuBrand(String cpuBrand) {
    
    this.cpuBrand = cpuBrand;
    return this;
  }

   /**
   * Get cpuBrand
   * @return cpuBrand
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getCpuBrand() {
    return cpuBrand;
  }


  public void setCpuBrand(String cpuBrand) {
    this.cpuBrand = cpuBrand;
  }


  public Host cpuFanSpeed(List<Double> cpuFanSpeed) {
    
    this.cpuFanSpeed = cpuFanSpeed;
    return this;
  }

  public Host addCpuFanSpeedItem(Double cpuFanSpeedItem) {
    this.cpuFanSpeed.add(cpuFanSpeedItem);
    return this;
  }

   /**
   * Get cpuFanSpeed
   * @return cpuFanSpeed
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<Double> getCpuFanSpeed() {
    return cpuFanSpeed;
  }


  public void setCpuFanSpeed(List<Double> cpuFanSpeed) {
    this.cpuFanSpeed = cpuFanSpeed;
  }


  public Host cpuFanSpeedUnit(CpuFanSpeedUnit cpuFanSpeedUnit) {
    
    this.cpuFanSpeedUnit = cpuFanSpeedUnit;
    return this;
  }

   /**
   * Get cpuFanSpeedUnit
   * @return cpuFanSpeedUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CpuFanSpeedUnit getCpuFanSpeedUnit() {
    return cpuFanSpeedUnit;
  }


  public void setCpuFanSpeedUnit(CpuFanSpeedUnit cpuFanSpeedUnit) {
    this.cpuFanSpeedUnit = cpuFanSpeedUnit;
  }


  public Host cpuHzPerCore(Double cpuHzPerCore) {
    
    this.cpuHzPerCore = cpuHzPerCore;
    return this;
  }

   /**
   * Get cpuHzPerCore
   * @return cpuHzPerCore
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getCpuHzPerCore() {
    return cpuHzPerCore;
  }


  public void setCpuHzPerCore(Double cpuHzPerCore) {
    this.cpuHzPerCore = cpuHzPerCore;
  }


  public Host cpuModel(String cpuModel) {
    
    this.cpuModel = cpuModel;
    return this;
  }

   /**
   * Get cpuModel
   * @return cpuModel
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getCpuModel() {
    return cpuModel;
  }


  public void setCpuModel(String cpuModel) {
    this.cpuModel = cpuModel;
  }


  public Host cpuTemperatureCelsius(List<Double> cpuTemperatureCelsius) {
    
    this.cpuTemperatureCelsius = cpuTemperatureCelsius;
    return this;
  }

  public Host addCpuTemperatureCelsiusItem(Double cpuTemperatureCelsiusItem) {
    this.cpuTemperatureCelsius.add(cpuTemperatureCelsiusItem);
    return this;
  }

   /**
   * Get cpuTemperatureCelsius
   * @return cpuTemperatureCelsius
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<Double> getCpuTemperatureCelsius() {
    return cpuTemperatureCelsius;
  }


  public void setCpuTemperatureCelsius(List<Double> cpuTemperatureCelsius) {
    this.cpuTemperatureCelsius = cpuTemperatureCelsius;
  }


  public Host dataIp(String dataIp) {
    
    this.dataIp = dataIp;
    return this;
  }

   /**
   * Get dataIp
   * @return dataIp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDataIp() {
    return dataIp;
  }


  public void setDataIp(String dataIp) {
    this.dataIp = dataIp;
  }


  public Host disks(List<AlertRuleCluster> disks) {
    
    this.disks = disks;
    return this;
  }

  public Host addDisksItem(AlertRuleCluster disksItem) {
    if (this.disks == null) {
      this.disks = new ArrayList<AlertRuleCluster>();
    }
    this.disks.add(disksItem);
    return this;
  }

   /**
   * Get disks
   * @return disks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AlertRuleCluster> getDisks() {
    return disks;
  }


  public void setDisks(List<AlertRuleCluster> disks) {
    this.disks = disks;
  }


  public Host failureDataSpace(Double failureDataSpace) {
    
    this.failureDataSpace = failureDataSpace;
    return this;
  }

   /**
   * Get failureDataSpace
   * @return failureDataSpace
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getFailureDataSpace() {
    return failureDataSpace;
  }


  public void setFailureDataSpace(Double failureDataSpace) {
    this.failureDataSpace = failureDataSpace;
  }


  public Host hddDataCapacity(Double hddDataCapacity) {
    
    this.hddDataCapacity = hddDataCapacity;
    return this;
  }

   /**
   * Get hddDataCapacity
   * @return hddDataCapacity
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getHddDataCapacity() {
    return hddDataCapacity;
  }


  public void setHddDataCapacity(Double hddDataCapacity) {
    this.hddDataCapacity = hddDataCapacity;
  }


  public Host hddDiskCount(Double hddDiskCount) {
    
    this.hddDiskCount = hddDiskCount;
    return this;
  }

   /**
   * Get hddDiskCount
   * @return hddDiskCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getHddDiskCount() {
    return hddDiskCount;
  }


  public void setHddDiskCount(Double hddDiskCount) {
    this.hddDiskCount = hddDiskCount;
  }


  public Host id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Host ipmi(AlertAlertRule ipmi) {
    
    this.ipmi = ipmi;
    return this;
  }

   /**
   * Get ipmi
   * @return ipmi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AlertAlertRule getIpmi() {
    return ipmi;
  }


  public void setIpmi(AlertAlertRule ipmi) {
    this.ipmi = ipmi;
  }


  public Host isOsInRaid1(Boolean isOsInRaid1) {
    
    this.isOsInRaid1 = isOsInRaid1;
    return this;
  }

   /**
   * Get isOsInRaid1
   * @return isOsInRaid1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsOsInRaid1() {
    return isOsInRaid1;
  }


  public void setIsOsInRaid1(Boolean isOsInRaid1) {
    this.isOsInRaid1 = isOsInRaid1;
  }


  public Host labels(List<BrickTopoPowers> labels) {
    
    this.labels = labels;
    return this;
  }

  public Host addLabelsItem(BrickTopoPowers labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<BrickTopoPowers>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * Get labels
   * @return labels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<BrickTopoPowers> getLabels() {
    return labels;
  }


  public void setLabels(List<BrickTopoPowers> labels) {
    this.labels = labels;
  }


  public Host localId(String localId) {
    
    this.localId = localId;
    return this;
  }

   /**
   * Get localId
   * @return localId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getLocalId() {
    return localId;
  }


  public void setLocalId(String localId) {
    this.localId = localId;
  }


  public Host lsmCapDiskSafeUmount(Boolean lsmCapDiskSafeUmount) {
    
    this.lsmCapDiskSafeUmount = lsmCapDiskSafeUmount;
    return this;
  }

   /**
   * Get lsmCapDiskSafeUmount
   * @return lsmCapDiskSafeUmount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getLsmCapDiskSafeUmount() {
    return lsmCapDiskSafeUmount;
  }


  public void setLsmCapDiskSafeUmount(Boolean lsmCapDiskSafeUmount) {
    this.lsmCapDiskSafeUmount = lsmCapDiskSafeUmount;
  }


  public Host managementIp(String managementIp) {
    
    this.managementIp = managementIp;
    return this;
  }

   /**
   * Get managementIp
   * @return managementIp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getManagementIp() {
    return managementIp;
  }


  public void setManagementIp(String managementIp) {
    this.managementIp = managementIp;
  }


  public Host model(String model) {
    
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getModel() {
    return model;
  }


  public void setModel(String model) {
    this.model = model;
  }


  public Host name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Host nestedVirtualization(Boolean nestedVirtualization) {
    
    this.nestedVirtualization = nestedVirtualization;
    return this;
  }

   /**
   * Get nestedVirtualization
   * @return nestedVirtualization
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getNestedVirtualization() {
    return nestedVirtualization;
  }


  public void setNestedVirtualization(Boolean nestedVirtualization) {
    this.nestedVirtualization = nestedVirtualization;
  }


  public Host nicCount(Double nicCount) {
    
    this.nicCount = nicCount;
    return this;
  }

   /**
   * Get nicCount
   * @return nicCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getNicCount() {
    return nicCount;
  }


  public void setNicCount(Double nicCount) {
    this.nicCount = nicCount;
  }


  public Host nics(List<AlertRuleCluster> nics) {
    
    this.nics = nics;
    return this;
  }

  public Host addNicsItem(AlertRuleCluster nicsItem) {
    if (this.nics == null) {
      this.nics = new ArrayList<AlertRuleCluster>();
    }
    this.nics.add(nicsItem);
    return this;
  }

   /**
   * Get nics
   * @return nics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AlertRuleCluster> getNics() {
    return nics;
  }


  public void setNics(List<AlertRuleCluster> nics) {
    this.nics = nics;
  }


  public Host nodeTopoLocalId(String nodeTopoLocalId) {
    
    this.nodeTopoLocalId = nodeTopoLocalId;
    return this;
  }

   /**
   * Get nodeTopoLocalId
   * @return nodeTopoLocalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNodeTopoLocalId() {
    return nodeTopoLocalId;
  }


  public void setNodeTopoLocalId(String nodeTopoLocalId) {
    this.nodeTopoLocalId = nodeTopoLocalId;
  }


  public Host osMemoryBytes(Double osMemoryBytes) {
    
    this.osMemoryBytes = osMemoryBytes;
    return this;
  }

   /**
   * Get osMemoryBytes
   * @return osMemoryBytes
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getOsMemoryBytes() {
    return osMemoryBytes;
  }


  public void setOsMemoryBytes(Double osMemoryBytes) {
    this.osMemoryBytes = osMemoryBytes;
  }


  public Host osVersion(String osVersion) {
    
    this.osVersion = osVersion;
    return this;
  }

   /**
   * Get osVersion
   * @return osVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOsVersion() {
    return osVersion;
  }


  public void setOsVersion(String osVersion) {
    this.osVersion = osVersion;
  }


  public Host pmemDimmCapacity(Double pmemDimmCapacity) {
    
    this.pmemDimmCapacity = pmemDimmCapacity;
    return this;
  }

   /**
   * Get pmemDimmCapacity
   * @return pmemDimmCapacity
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getPmemDimmCapacity() {
    return pmemDimmCapacity;
  }


  public void setPmemDimmCapacity(Double pmemDimmCapacity) {
    this.pmemDimmCapacity = pmemDimmCapacity;
  }


  public Host pmemDimmCount(Double pmemDimmCount) {
    
    this.pmemDimmCount = pmemDimmCount;
    return this;
  }

   /**
   * Get pmemDimmCount
   * @return pmemDimmCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getPmemDimmCount() {
    return pmemDimmCount;
  }


  public void setPmemDimmCount(Double pmemDimmCount) {
    this.pmemDimmCount = pmemDimmCount;
  }


  public Host pmemDimms(List<AlertRuleCluster> pmemDimms) {
    
    this.pmemDimms = pmemDimms;
    return this;
  }

  public Host addPmemDimmsItem(AlertRuleCluster pmemDimmsItem) {
    if (this.pmemDimms == null) {
      this.pmemDimms = new ArrayList<AlertRuleCluster>();
    }
    this.pmemDimms.add(pmemDimmsItem);
    return this;
  }

   /**
   * Get pmemDimms
   * @return pmemDimms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AlertRuleCluster> getPmemDimms() {
    return pmemDimms;
  }


  public void setPmemDimms(List<AlertRuleCluster> pmemDimms) {
    this.pmemDimms = pmemDimms;
  }


  public Host pmemDiskCount(Double pmemDiskCount) {
    
    this.pmemDiskCount = pmemDiskCount;
    return this;
  }

   /**
   * Get pmemDiskCount
   * @return pmemDiskCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getPmemDiskCount() {
    return pmemDiskCount;
  }


  public void setPmemDiskCount(Double pmemDiskCount) {
    this.pmemDiskCount = pmemDiskCount;
  }


  public Host provisionedCpuCores(Double provisionedCpuCores) {
    
    this.provisionedCpuCores = provisionedCpuCores;
    return this;
  }

   /**
   * Get provisionedCpuCores
   * @return provisionedCpuCores
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getProvisionedCpuCores() {
    return provisionedCpuCores;
  }


  public void setProvisionedCpuCores(Double provisionedCpuCores) {
    this.provisionedCpuCores = provisionedCpuCores;
  }


  public Host provisionedMemoryBytes(Double provisionedMemoryBytes) {
    
    this.provisionedMemoryBytes = provisionedMemoryBytes;
    return this;
  }

   /**
   * Get provisionedMemoryBytes
   * @return provisionedMemoryBytes
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getProvisionedMemoryBytes() {
    return provisionedMemoryBytes;
  }


  public void setProvisionedMemoryBytes(Double provisionedMemoryBytes) {
    this.provisionedMemoryBytes = provisionedMemoryBytes;
  }


  public Host runningPauseVmMemoryBytes(Double runningPauseVmMemoryBytes) {
    
    this.runningPauseVmMemoryBytes = runningPauseVmMemoryBytes;
    return this;
  }

   /**
   * Get runningPauseVmMemoryBytes
   * @return runningPauseVmMemoryBytes
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getRunningPauseVmMemoryBytes() {
    return runningPauseVmMemoryBytes;
  }


  public void setRunningPauseVmMemoryBytes(Double runningPauseVmMemoryBytes) {
    this.runningPauseVmMemoryBytes = runningPauseVmMemoryBytes;
  }


  public Host runningVmNum(Double runningVmNum) {
    
    this.runningVmNum = runningVmNum;
    return this;
  }

   /**
   * Get runningVmNum
   * @return runningVmNum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getRunningVmNum() {
    return runningVmNum;
  }


  public void setRunningVmNum(Double runningVmNum) {
    this.runningVmNum = runningVmNum;
  }


  public Host scvmCpu(Double scvmCpu) {
    
    this.scvmCpu = scvmCpu;
    return this;
  }

   /**
   * Get scvmCpu
   * @return scvmCpu
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getScvmCpu() {
    return scvmCpu;
  }


  public void setScvmCpu(Double scvmCpu) {
    this.scvmCpu = scvmCpu;
  }


  public Host scvmMemory(Double scvmMemory) {
    
    this.scvmMemory = scvmMemory;
    return this;
  }

   /**
   * Get scvmMemory
   * @return scvmMemory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getScvmMemory() {
    return scvmMemory;
  }


  public void setScvmMemory(Double scvmMemory) {
    this.scvmMemory = scvmMemory;
  }


  public Host scvmName(String scvmName) {
    
    this.scvmName = scvmName;
    return this;
  }

   /**
   * Get scvmName
   * @return scvmName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getScvmName() {
    return scvmName;
  }


  public void setScvmName(String scvmName) {
    this.scvmName = scvmName;
  }


  public Host serial(String serial) {
    
    this.serial = serial;
    return this;
  }

   /**
   * Get serial
   * @return serial
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSerial() {
    return serial;
  }


  public void setSerial(String serial) {
    this.serial = serial;
  }


  public Host ssdDataCapacity(Double ssdDataCapacity) {
    
    this.ssdDataCapacity = ssdDataCapacity;
    return this;
  }

   /**
   * Get ssdDataCapacity
   * @return ssdDataCapacity
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getSsdDataCapacity() {
    return ssdDataCapacity;
  }


  public void setSsdDataCapacity(Double ssdDataCapacity) {
    this.ssdDataCapacity = ssdDataCapacity;
  }


  public Host ssdDiskCount(Double ssdDiskCount) {
    
    this.ssdDiskCount = ssdDiskCount;
    return this;
  }

   /**
   * Get ssdDiskCount
   * @return ssdDiskCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getSsdDiskCount() {
    return ssdDiskCount;
  }


  public void setSsdDiskCount(Double ssdDiskCount) {
    this.ssdDiskCount = ssdDiskCount;
  }


  public Host state(HostState state) {
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public HostState getState() {
    return state;
  }


  public void setState(HostState state) {
    this.state = state;
  }


  public Host status(HostStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public HostStatus getStatus() {
    return status;
  }


  public void setStatus(HostStatus status) {
    this.status = status;
  }


  public Host stoppedVmNum(Double stoppedVmNum) {
    
    this.stoppedVmNum = stoppedVmNum;
    return this;
  }

   /**
   * Get stoppedVmNum
   * @return stoppedVmNum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getStoppedVmNum() {
    return stoppedVmNum;
  }


  public void setStoppedVmNum(Double stoppedVmNum) {
    this.stoppedVmNum = stoppedVmNum;
  }


  public Host suspendedVmNum(Double suspendedVmNum) {
    
    this.suspendedVmNum = suspendedVmNum;
    return this;
  }

   /**
   * Get suspendedVmNum
   * @return suspendedVmNum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getSuspendedVmNum() {
    return suspendedVmNum;
  }


  public void setSuspendedVmNum(Double suspendedVmNum) {
    this.suspendedVmNum = suspendedVmNum;
  }


  public Host totalCacheCapacity(Double totalCacheCapacity) {
    
    this.totalCacheCapacity = totalCacheCapacity;
    return this;
  }

   /**
   * Get totalCacheCapacity
   * @return totalCacheCapacity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getTotalCacheCapacity() {
    return totalCacheCapacity;
  }


  public void setTotalCacheCapacity(Double totalCacheCapacity) {
    this.totalCacheCapacity = totalCacheCapacity;
  }


  public Host totalCpuCores(Double totalCpuCores) {
    
    this.totalCpuCores = totalCpuCores;
    return this;
  }

   /**
   * Get totalCpuCores
   * @return totalCpuCores
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getTotalCpuCores() {
    return totalCpuCores;
  }


  public void setTotalCpuCores(Double totalCpuCores) {
    this.totalCpuCores = totalCpuCores;
  }


  public Host totalCpuHz(Double totalCpuHz) {
    
    this.totalCpuHz = totalCpuHz;
    return this;
  }

   /**
   * Get totalCpuHz
   * @return totalCpuHz
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getTotalCpuHz() {
    return totalCpuHz;
  }


  public void setTotalCpuHz(Double totalCpuHz) {
    this.totalCpuHz = totalCpuHz;
  }


  public Host totalDataCapacity(Double totalDataCapacity) {
    
    this.totalDataCapacity = totalDataCapacity;
    return this;
  }

   /**
   * Get totalDataCapacity
   * @return totalDataCapacity
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getTotalDataCapacity() {
    return totalDataCapacity;
  }


  public void setTotalDataCapacity(Double totalDataCapacity) {
    this.totalDataCapacity = totalDataCapacity;
  }


  public Host totalMemoryBytes(Double totalMemoryBytes) {
    
    this.totalMemoryBytes = totalMemoryBytes;
    return this;
  }

   /**
   * Get totalMemoryBytes
   * @return totalMemoryBytes
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getTotalMemoryBytes() {
    return totalMemoryBytes;
  }


  public void setTotalMemoryBytes(Double totalMemoryBytes) {
    this.totalMemoryBytes = totalMemoryBytes;
  }


  public Host usbDevices(List<AlertRuleCluster> usbDevices) {
    
    this.usbDevices = usbDevices;
    return this;
  }

  public Host addUsbDevicesItem(AlertRuleCluster usbDevicesItem) {
    if (this.usbDevices == null) {
      this.usbDevices = new ArrayList<AlertRuleCluster>();
    }
    this.usbDevices.add(usbDevicesItem);
    return this;
  }

   /**
   * Get usbDevices
   * @return usbDevices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AlertRuleCluster> getUsbDevices() {
    return usbDevices;
  }


  public void setUsbDevices(List<AlertRuleCluster> usbDevices) {
    this.usbDevices = usbDevices;
  }


  public Host usedCpuHz(Double usedCpuHz) {
    
    this.usedCpuHz = usedCpuHz;
    return this;
  }

   /**
   * Get usedCpuHz
   * @return usedCpuHz
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getUsedCpuHz() {
    return usedCpuHz;
  }


  public void setUsedCpuHz(Double usedCpuHz) {
    this.usedCpuHz = usedCpuHz;
  }


  public Host usedDataSpace(Double usedDataSpace) {
    
    this.usedDataSpace = usedDataSpace;
    return this;
  }

   /**
   * Get usedDataSpace
   * @return usedDataSpace
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getUsedDataSpace() {
    return usedDataSpace;
  }


  public void setUsedDataSpace(Double usedDataSpace) {
    this.usedDataSpace = usedDataSpace;
  }


  public Host usedMemoryBytes(Double usedMemoryBytes) {
    
    this.usedMemoryBytes = usedMemoryBytes;
    return this;
  }

   /**
   * Get usedMemoryBytes
   * @return usedMemoryBytes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getUsedMemoryBytes() {
    return usedMemoryBytes;
  }


  public void setUsedMemoryBytes(Double usedMemoryBytes) {
    this.usedMemoryBytes = usedMemoryBytes;
  }


  public Host vmNum(Double vmNum) {
    
    this.vmNum = vmNum;
    return this;
  }

   /**
   * Get vmNum
   * @return vmNum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getVmNum() {
    return vmNum;
  }


  public void setVmNum(Double vmNum) {
    this.vmNum = vmNum;
  }


  public Host vmotionIp(String vmotionIp) {
    
    this.vmotionIp = vmotionIp;
    return this;
  }

   /**
   * Get vmotionIp
   * @return vmotionIp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVmotionIp() {
    return vmotionIp;
  }


  public void setVmotionIp(String vmotionIp) {
    this.vmotionIp = vmotionIp;
  }


  public Host vms(List<AlertRuleCluster> vms) {
    
    this.vms = vms;
    return this;
  }

  public Host addVmsItem(AlertRuleCluster vmsItem) {
    if (this.vms == null) {
      this.vms = new ArrayList<AlertRuleCluster>();
    }
    this.vms.add(vmsItem);
    return this;
  }

   /**
   * Get vms
   * @return vms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AlertRuleCluster> getVms() {
    return vms;
  }


  public void setVms(List<AlertRuleCluster> vms) {
    this.vms = vms;
  }


  public Host vsphereEsxiAccount(AlertAlertRule vsphereEsxiAccount) {
    
    this.vsphereEsxiAccount = vsphereEsxiAccount;
    return this;
  }

   /**
   * Get vsphereEsxiAccount
   * @return vsphereEsxiAccount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AlertAlertRule getVsphereEsxiAccount() {
    return vsphereEsxiAccount;
  }


  public void setVsphereEsxiAccount(AlertAlertRule vsphereEsxiAccount) {
    this.vsphereEsxiAccount = vsphereEsxiAccount;
  }


  public Host withFasterSsdAsCache(Boolean withFasterSsdAsCache) {
    
    this.withFasterSsdAsCache = withFasterSsdAsCache;
    return this;
  }

   /**
   * Get withFasterSsdAsCache
   * @return withFasterSsdAsCache
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getWithFasterSsdAsCache() {
    return withFasterSsdAsCache;
  }


  public void setWithFasterSsdAsCache(Boolean withFasterSsdAsCache) {
    this.withFasterSsdAsCache = withFasterSsdAsCache;
  }


  public Host zone(AlertAlertRule zone) {
    
    this.zone = zone;
    return this;
  }

   /**
   * Get zone
   * @return zone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AlertAlertRule getZone() {
    return zone;
  }


  public void setZone(AlertAlertRule zone) {
    this.zone = zone;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Host host = (Host) o;
    return Objects.equals(this.accessIp, host.accessIp) &&
        Objects.equals(this.allocatableMemoryBytes, host.allocatableMemoryBytes) &&
        Objects.equals(this.chunkId, host.chunkId) &&
        Objects.equals(this.cluster, host.cluster) &&
        Objects.equals(this.compatibleCpuModels, host.compatibleCpuModels) &&
        Objects.equals(this.cpuBrand, host.cpuBrand) &&
        Objects.equals(this.cpuFanSpeed, host.cpuFanSpeed) &&
        Objects.equals(this.cpuFanSpeedUnit, host.cpuFanSpeedUnit) &&
        Objects.equals(this.cpuHzPerCore, host.cpuHzPerCore) &&
        Objects.equals(this.cpuModel, host.cpuModel) &&
        Objects.equals(this.cpuTemperatureCelsius, host.cpuTemperatureCelsius) &&
        Objects.equals(this.dataIp, host.dataIp) &&
        Objects.equals(this.disks, host.disks) &&
        Objects.equals(this.failureDataSpace, host.failureDataSpace) &&
        Objects.equals(this.hddDataCapacity, host.hddDataCapacity) &&
        Objects.equals(this.hddDiskCount, host.hddDiskCount) &&
        Objects.equals(this.id, host.id) &&
        Objects.equals(this.ipmi, host.ipmi) &&
        Objects.equals(this.isOsInRaid1, host.isOsInRaid1) &&
        Objects.equals(this.labels, host.labels) &&
        Objects.equals(this.localId, host.localId) &&
        Objects.equals(this.lsmCapDiskSafeUmount, host.lsmCapDiskSafeUmount) &&
        Objects.equals(this.managementIp, host.managementIp) &&
        Objects.equals(this.model, host.model) &&
        Objects.equals(this.name, host.name) &&
        Objects.equals(this.nestedVirtualization, host.nestedVirtualization) &&
        Objects.equals(this.nicCount, host.nicCount) &&
        Objects.equals(this.nics, host.nics) &&
        Objects.equals(this.nodeTopoLocalId, host.nodeTopoLocalId) &&
        Objects.equals(this.osMemoryBytes, host.osMemoryBytes) &&
        Objects.equals(this.osVersion, host.osVersion) &&
        Objects.equals(this.pmemDimmCapacity, host.pmemDimmCapacity) &&
        Objects.equals(this.pmemDimmCount, host.pmemDimmCount) &&
        Objects.equals(this.pmemDimms, host.pmemDimms) &&
        Objects.equals(this.pmemDiskCount, host.pmemDiskCount) &&
        Objects.equals(this.provisionedCpuCores, host.provisionedCpuCores) &&
        Objects.equals(this.provisionedMemoryBytes, host.provisionedMemoryBytes) &&
        Objects.equals(this.runningPauseVmMemoryBytes, host.runningPauseVmMemoryBytes) &&
        Objects.equals(this.runningVmNum, host.runningVmNum) &&
        Objects.equals(this.scvmCpu, host.scvmCpu) &&
        Objects.equals(this.scvmMemory, host.scvmMemory) &&
        Objects.equals(this.scvmName, host.scvmName) &&
        Objects.equals(this.serial, host.serial) &&
        Objects.equals(this.ssdDataCapacity, host.ssdDataCapacity) &&
        Objects.equals(this.ssdDiskCount, host.ssdDiskCount) &&
        Objects.equals(this.state, host.state) &&
        Objects.equals(this.status, host.status) &&
        Objects.equals(this.stoppedVmNum, host.stoppedVmNum) &&
        Objects.equals(this.suspendedVmNum, host.suspendedVmNum) &&
        Objects.equals(this.totalCacheCapacity, host.totalCacheCapacity) &&
        Objects.equals(this.totalCpuCores, host.totalCpuCores) &&
        Objects.equals(this.totalCpuHz, host.totalCpuHz) &&
        Objects.equals(this.totalDataCapacity, host.totalDataCapacity) &&
        Objects.equals(this.totalMemoryBytes, host.totalMemoryBytes) &&
        Objects.equals(this.usbDevices, host.usbDevices) &&
        Objects.equals(this.usedCpuHz, host.usedCpuHz) &&
        Objects.equals(this.usedDataSpace, host.usedDataSpace) &&
        Objects.equals(this.usedMemoryBytes, host.usedMemoryBytes) &&
        Objects.equals(this.vmNum, host.vmNum) &&
        Objects.equals(this.vmotionIp, host.vmotionIp) &&
        Objects.equals(this.vms, host.vms) &&
        Objects.equals(this.vsphereEsxiAccount, host.vsphereEsxiAccount) &&
        Objects.equals(this.withFasterSsdAsCache, host.withFasterSsdAsCache) &&
        Objects.equals(this.zone, host.zone);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessIp, allocatableMemoryBytes, chunkId, cluster, compatibleCpuModels, cpuBrand, cpuFanSpeed, cpuFanSpeedUnit, cpuHzPerCore, cpuModel, cpuTemperatureCelsius, dataIp, disks, failureDataSpace, hddDataCapacity, hddDiskCount, id, ipmi, isOsInRaid1, labels, localId, lsmCapDiskSafeUmount, managementIp, model, name, nestedVirtualization, nicCount, nics, nodeTopoLocalId, osMemoryBytes, osVersion, pmemDimmCapacity, pmemDimmCount, pmemDimms, pmemDiskCount, provisionedCpuCores, provisionedMemoryBytes, runningPauseVmMemoryBytes, runningVmNum, scvmCpu, scvmMemory, scvmName, serial, ssdDataCapacity, ssdDiskCount, state, status, stoppedVmNum, suspendedVmNum, totalCacheCapacity, totalCpuCores, totalCpuHz, totalDataCapacity, totalMemoryBytes, usbDevices, usedCpuHz, usedDataSpace, usedMemoryBytes, vmNum, vmotionIp, vms, vsphereEsxiAccount, withFasterSsdAsCache, zone);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Host {\n");
    sb.append("    accessIp: ").append(toIndentedString(accessIp)).append("\n");
    sb.append("    allocatableMemoryBytes: ").append(toIndentedString(allocatableMemoryBytes)).append("\n");
    sb.append("    chunkId: ").append(toIndentedString(chunkId)).append("\n");
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("    compatibleCpuModels: ").append(toIndentedString(compatibleCpuModels)).append("\n");
    sb.append("    cpuBrand: ").append(toIndentedString(cpuBrand)).append("\n");
    sb.append("    cpuFanSpeed: ").append(toIndentedString(cpuFanSpeed)).append("\n");
    sb.append("    cpuFanSpeedUnit: ").append(toIndentedString(cpuFanSpeedUnit)).append("\n");
    sb.append("    cpuHzPerCore: ").append(toIndentedString(cpuHzPerCore)).append("\n");
    sb.append("    cpuModel: ").append(toIndentedString(cpuModel)).append("\n");
    sb.append("    cpuTemperatureCelsius: ").append(toIndentedString(cpuTemperatureCelsius)).append("\n");
    sb.append("    dataIp: ").append(toIndentedString(dataIp)).append("\n");
    sb.append("    disks: ").append(toIndentedString(disks)).append("\n");
    sb.append("    failureDataSpace: ").append(toIndentedString(failureDataSpace)).append("\n");
    sb.append("    hddDataCapacity: ").append(toIndentedString(hddDataCapacity)).append("\n");
    sb.append("    hddDiskCount: ").append(toIndentedString(hddDiskCount)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ipmi: ").append(toIndentedString(ipmi)).append("\n");
    sb.append("    isOsInRaid1: ").append(toIndentedString(isOsInRaid1)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    localId: ").append(toIndentedString(localId)).append("\n");
    sb.append("    lsmCapDiskSafeUmount: ").append(toIndentedString(lsmCapDiskSafeUmount)).append("\n");
    sb.append("    managementIp: ").append(toIndentedString(managementIp)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nestedVirtualization: ").append(toIndentedString(nestedVirtualization)).append("\n");
    sb.append("    nicCount: ").append(toIndentedString(nicCount)).append("\n");
    sb.append("    nics: ").append(toIndentedString(nics)).append("\n");
    sb.append("    nodeTopoLocalId: ").append(toIndentedString(nodeTopoLocalId)).append("\n");
    sb.append("    osMemoryBytes: ").append(toIndentedString(osMemoryBytes)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("    pmemDimmCapacity: ").append(toIndentedString(pmemDimmCapacity)).append("\n");
    sb.append("    pmemDimmCount: ").append(toIndentedString(pmemDimmCount)).append("\n");
    sb.append("    pmemDimms: ").append(toIndentedString(pmemDimms)).append("\n");
    sb.append("    pmemDiskCount: ").append(toIndentedString(pmemDiskCount)).append("\n");
    sb.append("    provisionedCpuCores: ").append(toIndentedString(provisionedCpuCores)).append("\n");
    sb.append("    provisionedMemoryBytes: ").append(toIndentedString(provisionedMemoryBytes)).append("\n");
    sb.append("    runningPauseVmMemoryBytes: ").append(toIndentedString(runningPauseVmMemoryBytes)).append("\n");
    sb.append("    runningVmNum: ").append(toIndentedString(runningVmNum)).append("\n");
    sb.append("    scvmCpu: ").append(toIndentedString(scvmCpu)).append("\n");
    sb.append("    scvmMemory: ").append(toIndentedString(scvmMemory)).append("\n");
    sb.append("    scvmName: ").append(toIndentedString(scvmName)).append("\n");
    sb.append("    serial: ").append(toIndentedString(serial)).append("\n");
    sb.append("    ssdDataCapacity: ").append(toIndentedString(ssdDataCapacity)).append("\n");
    sb.append("    ssdDiskCount: ").append(toIndentedString(ssdDiskCount)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    stoppedVmNum: ").append(toIndentedString(stoppedVmNum)).append("\n");
    sb.append("    suspendedVmNum: ").append(toIndentedString(suspendedVmNum)).append("\n");
    sb.append("    totalCacheCapacity: ").append(toIndentedString(totalCacheCapacity)).append("\n");
    sb.append("    totalCpuCores: ").append(toIndentedString(totalCpuCores)).append("\n");
    sb.append("    totalCpuHz: ").append(toIndentedString(totalCpuHz)).append("\n");
    sb.append("    totalDataCapacity: ").append(toIndentedString(totalDataCapacity)).append("\n");
    sb.append("    totalMemoryBytes: ").append(toIndentedString(totalMemoryBytes)).append("\n");
    sb.append("    usbDevices: ").append(toIndentedString(usbDevices)).append("\n");
    sb.append("    usedCpuHz: ").append(toIndentedString(usedCpuHz)).append("\n");
    sb.append("    usedDataSpace: ").append(toIndentedString(usedDataSpace)).append("\n");
    sb.append("    usedMemoryBytes: ").append(toIndentedString(usedMemoryBytes)).append("\n");
    sb.append("    vmNum: ").append(toIndentedString(vmNum)).append("\n");
    sb.append("    vmotionIp: ").append(toIndentedString(vmotionIp)).append("\n");
    sb.append("    vms: ").append(toIndentedString(vms)).append("\n");
    sb.append("    vsphereEsxiAccount: ").append(toIndentedString(vsphereEsxiAccount)).append("\n");
    sb.append("    withFasterSsdAsCache: ").append(toIndentedString(withFasterSsdAsCache)).append("\n");
    sb.append("    zone: ").append(toIndentedString(zone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

