/*
 * CloudTower APIs
 * cloudtower operation API and SDK
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartx.tower.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartx.tower.model.NestedLabel;
import com.smartx.tower.model.NestedNetworkPolicyRulePort;
import com.smartx.tower.model.NetworkPolicyRuleType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * NestedNetworkPolicyRule
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class NestedNetworkPolicyRule {
  public static final String SERIALIZED_NAME_IP_BLOCK = "ip_block";
  @SerializedName(SERIALIZED_NAME_IP_BLOCK)
  private String ipBlock;

  public static final String SERIALIZED_NAME_PORTS = "ports";
  @SerializedName(SERIALIZED_NAME_PORTS)
  private List<NestedNetworkPolicyRulePort> ports = null;

  public static final String SERIALIZED_NAME_SELECTOR = "selector";
  @SerializedName(SERIALIZED_NAME_SELECTOR)
  private List<NestedLabel> selector = null;

  public static final String SERIALIZED_NAME_SELECTOR_IDS = "selector_ids";
  @SerializedName(SERIALIZED_NAME_SELECTOR_IDS)
  private List<String> selectorIds = null;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private NetworkPolicyRuleType type;

  public NestedNetworkPolicyRule() { 
  }

  public NestedNetworkPolicyRule ipBlock(String ipBlock) {
    
    this.ipBlock = ipBlock;
    return this;
  }

   /**
   * Get ipBlock
   * @return ipBlock
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIpBlock() {
    return ipBlock;
  }


  public void setIpBlock(String ipBlock) {
    this.ipBlock = ipBlock;
  }


  public NestedNetworkPolicyRule ports(List<NestedNetworkPolicyRulePort> ports) {
    
    this.ports = ports;
    return this;
  }

  public NestedNetworkPolicyRule addPortsItem(NestedNetworkPolicyRulePort portsItem) {
    if (this.ports == null) {
      this.ports = new ArrayList<NestedNetworkPolicyRulePort>();
    }
    this.ports.add(portsItem);
    return this;
  }

   /**
   * Get ports
   * @return ports
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<NestedNetworkPolicyRulePort> getPorts() {
    return ports;
  }


  public void setPorts(List<NestedNetworkPolicyRulePort> ports) {
    this.ports = ports;
  }


  public NestedNetworkPolicyRule selector(List<NestedLabel> selector) {
    
    this.selector = selector;
    return this;
  }

  public NestedNetworkPolicyRule addSelectorItem(NestedLabel selectorItem) {
    if (this.selector == null) {
      this.selector = new ArrayList<NestedLabel>();
    }
    this.selector.add(selectorItem);
    return this;
  }

   /**
   * Get selector
   * @return selector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<NestedLabel> getSelector() {
    return selector;
  }


  public void setSelector(List<NestedLabel> selector) {
    this.selector = selector;
  }


  public NestedNetworkPolicyRule selectorIds(List<String> selectorIds) {
    
    this.selectorIds = selectorIds;
    return this;
  }

  public NestedNetworkPolicyRule addSelectorIdsItem(String selectorIdsItem) {
    if (this.selectorIds == null) {
      this.selectorIds = new ArrayList<String>();
    }
    this.selectorIds.add(selectorIdsItem);
    return this;
  }

   /**
   * Get selectorIds
   * @return selectorIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getSelectorIds() {
    return selectorIds;
  }


  public void setSelectorIds(List<String> selectorIds) {
    this.selectorIds = selectorIds;
  }


  public NestedNetworkPolicyRule type(NetworkPolicyRuleType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public NetworkPolicyRuleType getType() {
    return type;
  }


  public void setType(NetworkPolicyRuleType type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NestedNetworkPolicyRule nestedNetworkPolicyRule = (NestedNetworkPolicyRule) o;
    return Objects.equals(this.ipBlock, nestedNetworkPolicyRule.ipBlock) &&
        Objects.equals(this.ports, nestedNetworkPolicyRule.ports) &&
        Objects.equals(this.selector, nestedNetworkPolicyRule.selector) &&
        Objects.equals(this.selectorIds, nestedNetworkPolicyRule.selectorIds) &&
        Objects.equals(this.type, nestedNetworkPolicyRule.type);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(ipBlock, ports, selector, selectorIds, type);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NestedNetworkPolicyRule {\n");
    sb.append("    ipBlock: ").append(toIndentedString(ipBlock)).append("\n");
    sb.append("    ports: ").append(toIndentedString(ports)).append("\n");
    sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
    sb.append("    selectorIds: ").append(toIndentedString(selectorIds)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

